vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: /images/img
            upload_destination: '%kernel.project_dir%/public/assets/pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer